### ISSUE TITLE
Covariates correction in hla alleles association

### ISSUE THREAD

**Issue by Eduardo-Auer** [Genentech/midasHLA#43]
Hi, is it possible to use covariates to correct sex, age and other covariates in HLA alleles association analysis? I would like to confirm because I could not find an example in tutorial.

Example: 

HLA_model <- glm(disease ~ term + **sex** + **age**, data = HLA, family = binomial)

**Comment by mcjmigdal** [comment]
@Eduardo-Auer yes you can do that, that's how we intended the association analysis to work. In fact you should do that, as I recall it is also common to include first principal components to take into account patients stratification. You can check out one of Christian's publication eg. https://pmc.ncbi.nlm.nih.gov/articles/PMC9199883/ see Methods - Statistical analysis.

Also I would recommend to rewrite your model so that the covariates come first, and term is your last variable. The way R solves linear models is left to right , so if say allele has the same effect as age with your model specification you won't see the age effect.

**Comment by Eduardo-Auer** [comment]
> @Eduardo-Auer yes you can do that, that's how we intended the association analysis to work. In fact you should do that, as I recall it is also common to include first principal components to take into account patients stratification. You can check out one of Christian's publication eg. https://pmc.ncbi.nlm.nih.gov/articles/PMC9199883/ see Methods - Statistical analysis.
> 
> Also I would recommend to rewrite your model so that the covariates come first, and term is your last variable. The way R solves linear models is left to right , so if say allele has the same effect as age with your model specification you won't see the age effect.

Oh, I see. Thanks for the quick response, explanation, and suggestions!
